# Generated by Django 3.1 on 2020-08-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid',
            old_name='fever',
            new_name='password',
        ),
        migrations.AddField(
            model_name='covid',
            name='username',
            field=models.CharField(default=-1.0, max_length=20),
            preserve_default=False,
        ),
    ]
